main: net.dylanhansch.lavahub.Lavahub
name: Lavahub
version: 1.0
description: Master bukkit plugin for the Lavahub Network.
author: Dylan Hansch
website: http://dylanhansch.net/
commands:
    action:
        description: Action message
        usage: /<command> (message)
        aliases: [me]
    afk:
        description: Away-from-Keyboard
        usage: /<command> (reason)
    back:
        description: Teleport to last location before tp/warp/spawn/death
        usage: /<command>
    balance:
        description: Display current money balance of player
        usage: /<command> (player)
        aliases: [bal, money]
    balancetop:
        description: Display server economy
        usage: /<command>
        aliases: [baltop]
    clearinventory:
        description: Clear player inventory
        usage: /<command> (player)
        aliases: [clear, ci]
    delhome:
        description: Delete home
        usage: /<command>
    delwarp:
        description: Delete warp
        usage: /<command> (warp)
    deljail:
        description: Delete jail
        usage: /<command> (jail)
    economy:
        description: Manage server economy
        usage: /<command> (give|take|set|reset) (amount) (player)
        aliases: [eco]
    enchant:
        description: Enchant item in hand
        usage: /<command> (enchantmentname) (level)
    exp:
        description: Give, set or look at a player exp
        usage: /<command> (give|take|set|reset|show) (amount) (player)
    feed:
        description: Satisfy hunger
        usage: /<command> (player)
    fly:
        description: Toggle fly mode
        usage: /<command> (player)
    gamemode:
        description: Toggle game mode
        usage: /<command> (mode) (player)
        aliases: [gm]
    godmode:
        description: Toggle god mode
        usage: /<command> (player)
        aliases: [god]
    give:
        description: Give player item(s)
        usage: /<command> (itemID) (amount) (player)
        aliases: [i]
    heal:
        description: Heal player
        usage: /<command> (player)
    help:
        description: View list of available commands
        usage: /<command> (plugin) (page number)
    home:
        description: Teleport to home
        usage: /<command>
    inventorysee:
        description: View player inventory
        usage: /<command> (player)
        aliases: [invsee]
    itemid:
        description: Look up item ID of item in hand
        usage: /<command>
    kick:
        description: Kick player
        usage: /<command> (player) (reason)
    kickall
        description: Kick all players except issuer
        usage: /<command>
    kill:
        description: Kill player
        usage: /<command> (player)
    kit:
        description: Obtain specified kit or list available kit(s)
        usage: /<command> (kit)
    list:
        description: List online players
        usage: /<command>
        aliases: [who]
    message:
        description: Private message player
        usage: /<command> (player) (message)
        aliases: [whisper, tell]
    player:
        description: Player info, like IP Address, last join, total playtime, money, logout location
        usage: /<command> (player)
    portalset:
        description: Set current WorldEdit selection as portal
        usage: /<command> (portal)
    portaldel:
        description: Delete portal
        usage: /<command> (portal)
    portalprint:
        description: List portals
        usage: /<command>
    portaldest:
        description: Set portal destination
        usage: /<command> (portal)
    pay:
        description: Pay player
        usage: /<command> (player) (amount)
    rawmsg:
        description: Send raw message
        usage: /<command> (message)
    reply:
        description: Quick reply to last private message
        usage: /<command> (message)
        aliases: [r]
    remove:
        description: Removes all entities in world
        usage: /<command>
    say:
        description: Broadcast to local server
        usage: /<command> (message)
    spawn:
        description: Teleport player to spawn
        usage: /<command> (player)
    setspawn:
        description: Set server spawn
        usage: /<command>
    sethome:
        description: Set home
        usage: /<command>
    setjail:
        description: Set jail
        usage: /<command> (jail)
    setwarp:
        description: Set warp
        usage: /<command> (warp)
    stats:
        description: Server memory usage, uptime and tick info
        usage: /<command>
        aliases: [lag, mem, gc]
    sell:
        description: Sell item(s) in hand
        usage: /<command> (player) (price)
    socialspy:
        description: See all private messages and sign placements
        usage: /<command>
    speed:
        description: Set player move speed
        usage: /<command> (speed) (player)
    sudo:
        description: Force player to proform a command
        usage: /<command> (player) (command)
    time:
        description: Change world time
        usage: /<command> (day|noon|night)
    top:
        description: Teleport to highest block at your position
        usage: /<command>
    tpa:
        description: Send teleport request
        usage: /<command> (player)
    tpaccept:
        description: Accept teleport request
        usage: /<command>
    tpdeny:
        description: Deny teleport request
        usage: /<command>
    tpahere:
        description: Send teleport-here request
        usage: /<command> (player)
    tp:
        description: Teleport to player
        usage: /<command> (player)
    tphere:
        description: Teleport player to you
        usage: /<command> (player)
    tppos:
        description: Teleport to position
        usage: /<command> (x) (y) (z)
    vanish:
        description: Become invisible
        usage: /<command>
    warp:
        description: Teleport player to warp or list available warps
        usage: /<command> (page) (warp) (player)
    weather:
        description: Change world weather
        usage: /<command> (sun|storm|thunderstorm)
    worth:
        description: Display worth of item(s) in hand
        usage: /<command>
    world:
        description: Teleport to world
        usage: /<command> (world)    
permissions:
    lavahub.action:
        default: true
    lavahub.afk:
        default: true
    lavahub.back:
        default: op
    lavahub.balance:
        default: true
    lavahub.balancetop:
        default: true
    lavahub.clearinventory:
        default: true
    lavahub.clearinventory.others:
        default: op
    lavahub.delhome:
        default: true
    lavahub.delwarp:
        default: op
    lavahub.deljail:
        default: op
    lavahub.economy:
        default: op
    lavahub.enchant:
        default: op
    lavahub.exp:
        default: op
    lavahub.feed:
        default: op
    lavahub.feed.others:
        default: op
    lavahub.fly:
        default: op
    lavahub.fly.others
        default: op
    lavahub.gamemode:
        default: op
    lavahub.gamemode.others:
        default: op
    lavahub.godmode:
        default: op
    lavahub.godmode.others:
        default: op
    lavahub.give:
        default: op
    lavahub.give.others:
        default: op
    lavahub.heal:
        default: op
    lavahub.heal.others:
        default: op
    lavahub.help:
        default: true
    lavahub.home:
        default: true
    lavahub.inventorysee:
        default: op
    lavahub.itemid:
        default: true
    lavahub.kick:
        default: op
    lavahub.kickall
        default: op
    lavahub.kill:
        default: true
    lavahub.kill.others:
        default: op
    lavahub.kit:
        default: op
    lavahub.list:
        default: true
    lavahub.message:
        default: true
    lavahub.player:
        default: op
    lavahub.portalset:
        default: op
    lavahub.portaldel:
        default: op
    lavahub.portalprint:
        default: true
    lavahub.portaldest:
        default: op
    lavahub.pay:
        default: true
    lavahub.rawmsg:
        default: op
    lavahub.reply:
        default: true
    lavahub.remove:
        default: op
    lavahub.say:
        default: op
    lavahub.spawn:
        default: true
    lavahub.setspawn:
        default: op
    lavahub.sethome:
        default: op
    lavahub.setjail:
        default: op
    lavahub.setwarp:
        default: op
    lavahub.stats:
        default: true
    lavahub.sell:
        default: true
    lavahub.socialspy:
        default: op
    lavahub.speed:
        default: op
    lavahub.sudo:
        default: op
    lavahub.time:
        default: op
    lavahub.top:
        default: op
    lavahub.tpa:
        default: true
    lavahub.tpaccept:
        default: true
    lavahub.tpdeny:
        default: true
    lavahub.tpahere:
        default: true
    lavahub.tp:
        default: op
    lavahub.tphere:
        default: op
    lavahub.tppos:
        default: op
    lavahub.vanish:
        default: op
    lavahub.warp:
        default: true
    lavahub.weather:
        default: op
    lavahub.worth:
        default: true
    lavahub.world:
        default: op